sudo: false
language: node_js

node_js:
  - 8
addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

install:
  - yarn install

script:
  - npm run lint
  - npm test
